# Build sources.
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY . ./
WORKDIR /src/src/Recollections.Api
RUN dotnet publish -c Release -r linux-arm -o /app

# Final image.
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim-arm32v7
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Recollections.Api.dll"]