FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    && rm -rf /var/lib/apt/lists/*