# Build sources.
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . ./
WORKDIR /src/src/Recollections.Api
RUN dotnet publish -c Release -r linux-arm -o /app

# Final image.
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim-arm32v7
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./Recollections.Api"]