FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim-arm32v7
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    && rm -rf /var/lib/apt/lists/*