# Build sources.
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY . ./
WORKDIR /src/src/Recollections.Api
RUN dotnet publish -c Release -r linux-arm -o /app

# Final image.
FROM neptuo/aspnet-system-drawing:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./Recollections.Api"]