name: API - build & push docker image

on:
  push:
    tags:
    - 'api-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (bullseye-slim)
        run: dotnet publish --os linux --arch x64 /t:PublishContainer
        shell: pwsh